Add examples test and enable multi-arch build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,18 +37,38 @@ jobs:
           context: .
           load: true
           push: false
-          tags: "localhost/local/app:dev"
+          tags: "localhost/fnndsc/pl-surfigures:dev"
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
       - name: Run pytest
         run: |
-          docker run -v "$GITHUB_WORKSPACE:/app:ro" -w /app localhost/local/app:dev \
+          docker run -v "$GITHUB_WORKSPACE:/app:ro" -w /app localhost/fnndsc/pl-surfigures:dev \
             pytest -o cache_dir=/tmp/pytest
+
+      - name: Run examples
+        run: |
+          output_dir=$(mktemp -d)
+          docker run --rm -u "$(id -u):$(id -g)" \
+            -v "$GITHUB_WORKSPACE/examples/incoming:/incoming:ro" \
+            -v "$output_dir:/outgoing:rw" \
+            localhost/fnndsc/pl-surfigures:dev surfigures /incoming /outgoing
+
+          outgoing=examples/outgoing
+          for expected_file in $(find "$outgoing" -type f | sed "s#$outgoing/##"); do
+            out_path="$output_dir/$expected_file"
+            printf "Checking output %s exists..." "$out_path"
+            if [ -f "$out_path" ]; then
+              echo "ok"
+            else
+              echo "not found"
+              exit 1
+            fi
+          done
 
   build:
     name: Build
     if: github.event_name == 'push' || github.event_name == 'release'
-    # needs: [ test ]  # uncomment to require passing tests
+    needs: [ test ]
     runs-on: ubuntu-22.04
 
     # A local registry helps us reuse the built image between steps
@@ -123,7 +143,7 @@ jobs:
             docker.io/${{ steps.determine.outputs.dock_image }}
             ghcr.io/${{ steps.determine.outputs.dock_image }}
           # if non-x86_84 architectures are supported, add them here
-          platforms: linux/amd64  #,linux/arm64,linux/ppc64le
+          platforms: linux/amd64,linux/arm64,linux/ppc64le
           push: true
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
